"""Shared provenance header for generated artefacts.

Every emitter stamps the amplitude-index convention into its output.  Mixing the two
up silently produces a circuit that prepares a bit-reversed state at plausible-looking
fidelity, which is the single easiest way to misuse a state-preparation tool.
"""

from __future__ import annotations

from ..circuit import Circuit

__all__ = ["header_lines"]

_ORDER_NOTE = {
    "big": (
        "amplitude index convention: BIG-endian -- qubit 0 is the most significant "
        "bit of the basis label (PennyLane qml.state(), textbook/OpenQASM reading)"
    ),
    "little": (
        "amplitude index convention: LITTLE-endian -- qubit 0 is the least "
        "significant bit of the basis label (Qiskit Statevector / Aer)"
    ),
}


def header_lines(circuit: Circuit) -> list[str]:
    """Comment body (without comment markers) describing the generated circuit."""
    metrics = circuit.metrics()
    return [
        "Generated by MPSynth -- approximate MPS state preparation",
        _ORDER_NOTE.get(circuit.amplitude_order, "amplitude index convention: unknown"),
        f"{metrics['n_qubits']} qubits, {metrics['cnot']} CNOTs, depth {metrics['depth']}"
        f" (two-qubit depth {metrics['two_qubit_depth']})",
    ]
